CHNA_REFERENCE_SOURCES = [
    {
        "name": "CDC Data and Statistics",
        "url": "https://www.cdc.gov/datastatistics/",
        "category": "Public Health",
        "geography_level": "National/State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Centers for Disease Control and Prevention. (n.d.). Data and statistics. CDC.",
    },
    {
        "name": "Tennessee Department of Health Statistics",
        "url": "https://www.tn.gov/health/health-program-areas/statistics.html",
        "category": "State Health",
        "geography_level": "State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Tennessee Department of Health. (n.d.). Health data and statistics.",
    },
    {
        "name": "Virginia Department of Health Data",
        "url": "https://www.vdh.virginia.gov/data/",
        "category": "State Health",
        "geography_level": "State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Virginia Department of Health. (n.d.). Health data and statistics.",
    },
    {
        "name": "US Census ACS",
        "url": "https://www.census.gov/programs-surveys/acs/",
        "category": "Demographics",
        "geography_level": "County/Census Tract",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "U.S. Census Bureau. (n.d.). American Community Survey.",
    },
    {
        "name": "US Census Decennial",
        "url": "https://www.census.gov/programs-surveys/decennial-census.html",
        "category": "Demographics",
        "geography_level": "National/State/County",
        "update_frequency": "Decennial",
        "owner": "Population Health",
        "citation": "U.S. Census Bureau. (n.d.). Decennial census.",
    },
    {
        "name": "SparkMap",
        "url": "https://www.sparkmap.org/",
        "category": "Population Health Platform",
        "geography_level": "County/Zip",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Spark Maps. (n.d.). Health and demographic data.",
    },
    {
        "name": "IRS Statistics",
        "url": "https://www.irs.gov/statistics",
        "category": "Economic",
        "geography_level": "National/State/County",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "Internal Revenue Service. (n.d.). Tax statistics.",
    },
    {
        "name": "BLS Data",
        "url": "https://www.bls.gov/data/",
        "category": "Employment",
        "geography_level": "National/State/Metro",
        "update_frequency": "Monthly",
        "owner": "Population Health",
        "citation": "Bureau of Labor Statistics. (n.d.). Employment statistics.",
    },
    {
        "name": "USDA Food Access Research Atlas",
        "url": "https://www.ers.usda.gov/data-products/food-access-research-atlas/",
        "category": "Food Access",
        "geography_level": "Census Tract",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "U.S. Department of Agriculture. (n.d.). Food access research atlas.",
    },
    {
        "name": "CMS Data",
        "url": "https://www.cms.gov/data",
        "category": "Healthcare Utilization",
        "geography_level": "National/State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Centers for Medicare & Medicaid Services. (n.d.). Medicare and Medicaid statistical data.",
    },
    {
        "name": "CDC PLACES",
        "url": "https://www.cdc.gov/places",
        "category": "Chronic Disease",
        "geography_level": "County/Census Tract",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "PLACES: Local Data for Better Health. (n.d.). Health data.",
    },
    {
        "name": "US Department of Education EDFacts",
        "url": "https://www2.ed.gov/about/inits/ed/edfacts/data-files/index.html",
        "category": "Education",
        "geography_level": "State/District",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "U.S. Department of Education. (n.d.). EDFacts data files.",
    },
    {
        "name": "DHS HIFLD",
        "url": "https://hifld-geoplatform.opendata.arcgis.com/",
        "category": "Infrastructure",
        "geography_level": "Point/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "Department of Homeland Security. (n.d.). Homeland Infrastructure Foundation-Level Data (HIFLD).",
    },
    {
        "name": "ACF Data",
        "url": "https://www.acf.hhs.gov/data",
        "category": "Child Welfare",
        "geography_level": "National/State",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "Administration for Children and Families. (n.d.). Child welfare data.",
    },
    {
        "name": "County Health Rankings",
        "url": "https://www.countyhealthrankings.org/",
        "category": "County Rankings",
        "geography_level": "County",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "County Health Rankings & Roadmaps. (n.d.). County Health Rankings data.",
    },
    {
        "name": "US DOT Data",
        "url": "https://www.transportation.gov/data",
        "category": "Transportation",
        "geography_level": "National/State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "U.S. Department of Transportation. (n.d.). Transportation statistics.",
    },
    {
        "name": "HUD Data",
        "url": "https://www.hud.gov/data",
        "category": "Housing",
        "geography_level": "National/State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "U.S. Department of Housing and Urban Development. (n.d.). Housing data and statistics.",
    },
    {
        "name": "US Department of Commerce Data",
        "url": "https://www.commerce.gov/data",
        "category": "Economic",
        "geography_level": "National/State",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "U.S. Department of Commerce. (n.d.). Economic data and statistics.",
    },
    {
        "name": "NCES CCD",
        "url": "https://nces.ed.gov/ccd",
        "category": "Education",
        "geography_level": "District/School",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "National Center for Education Statistics. (n.d.). Common Core of Data (CCD).",
    },
    {
        "name": "Urban Institute Debt in America",
        "url": "https://www.urban.org/policy-centers/cross-center-initiatives/debt-America",
        "category": "Economic",
        "geography_level": "National/State",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Urban Institute. (n.d.). Debt in America.",
    },
    {
        "name": "Neighborhood Atlas",
        "url": "https://www.neighborhoodatlas.medicine.wisc.edu/",
        "category": "Social Determinants",
        "geography_level": "Census Tract",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "University of Wisconsin-Madison. (n.d.). Neighborhood Atlas.",
    },
    {
        "name": "Feeding America Research",
        "url": "https://www.feedingamerica.org/research",
        "category": "Food Security",
        "geography_level": "National/State/County",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "Feeding America. (n.d.). Hunger and poverty in the United States.",
    },
    {
        "name": "Opportunity Insights Data",
        "url": "https://opportunityinsights.org/data/",
        "category": "Economic Mobility",
        "geography_level": "County/Census Tract",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Opportunity Insights. (n.d.). Data library.",
    },
    {
        "name": "University of Missouri CARES",
        "url": "https://cares.missouri.edu/",
        "category": "Community Data",
        "geography_level": "County/Census Tract",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "University of Missouri CARES. (n.d.). CARES data.",
    },
    {
        "name": "Penn State NERCRD",
        "url": "https://aese.psu.edu/nercrd",
        "category": "Rural Development",
        "geography_level": "County",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Penn State University NERCRD. (n.d.). Rural development data.",
    },
    {
        "name": "FBI Uniform Crime Reports",
        "url": "https://ucr.fbi.gov/",
        "category": "Public Safety",
        "geography_level": "National/State/County",
        "update_frequency": "Annual",
        "owner": "Population Health",
        "citation": "Federal Bureau of Investigation. (n.d.). Uniform Crime Reports.",
    },
    {
        "name": "Center for Neighborhood Technology",
        "url": "https://www.cnt.org/data/",
        "category": "Transportation/Housing",
        "geography_level": "Census Tract",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Center for Neighborhood Technology. (n.d.). Data and resources.",
    },
    {
        "name": "Opportunity Nation",
        "url": "https://opportunitynation.org/",
        "category": "Opportunity Index",
        "geography_level": "National/State",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Opportunity Nation. (n.d.). Opportunity Index.",
    },
    {
        "name": "EPA Data",
        "url": "https://www.epa.gov/data",
        "category": "Environment",
        "geography_level": "National/State/County",
        "update_frequency": "Varies",
        "owner": "Population Health",
        "citation": "U.S. Environmental Protection Agency. (n.d.). Environmental data.",
    },
    {
        "name": "Climate Impact Lab",
        "url": "https://www.impactlab.org/",
        "category": "Climate",
        "geography_level": "National/State/County",
        "update_frequency": "Periodic",
        "owner": "Population Health",
        "citation": "Climate Impact Lab. (n.d.). Climate data and projections.",
    },
    {
        "name": "US Drought Monitor",
        "url": "https://droughtmonitor.unl.edu/",
        "category": "Climate",
        "geography_level": "National/State/County",
        "update_frequency": "Weekly",
        "owner": "Population Health",
        "citation": "U.S. Drought Monitor. (n.d.). Drought data and reports.",
    },
]
